JustinGrote/ModuleFast

ModuleFast.ps1
ModuleFast.psm1
ModuleFast.tests.ps1

This pull request adds initial support for prerelease modules and enables the prerelease feature automatically if specified. It also includes updates to the Get-ModuleFastPlan function to filter and show prerelease modules based on user preferences.

🎉 Add Initial Prerelease Support and Enable Prerelease automatically if specified

---

ModuleFast.psm1
ModuleFast.tests.ps1

Enabling Prerelease support can now be specified on a per-specification basis by including a ! at the beginning or end of the modulename, in all formats.
Examples: 
- 'MyModule!' gets the latest prerelease version. '!MyModule' also works
- 'PnP.PowerShell!<2.3.0' returns 2.2.156-nightly
If -PreRelease is specified, all modules are evaulated for prerelease regardless of individual module Prerelease specifications.
Closes #7

🎉 Add per-spec Prerelease support

---

ModuleFast.ps1
ModuleFast.psm1
ModuleFast.tests.ps1

Fixes a lot of issues related to prerelease installation scenarios, and related tests added.

Fixes and improvements for module installation logic

---

ModuleFast.psm1
ModuleFast.tests.ps1
Test/Mocks/ModuleFast.requires.json
Test/Mocks/ModuleFast.requires.psd1
Test/Mocks/ModuleFastArray.requires.json

Adds support for SpecFiles, which are file based definitions of packages that should be installed. Initial support for psd1 and JSON based simple spec files.

🎉 Initial SpecFile Support

---

ModuleFast.psm1

In the current release (that the bit.ly-link points at) the now parameter `Specification` was called `ModulesToInstall` (plural), it was then renamed to `ModuleToInstall` (singylar) and now finally it is called `Specification`.
See blame:
https://github.com/JustinGrote/ModuleFast/blame/13f7890a076fc4df1ccea5b3a1a8ae1537ecb2f7/ModuleFast.psm1#L73C6-L73C22
This PR adds an alias to also handle the older parameter name `ModulesToInstall`.

Fix alias in Install-ModuleFast

---

ModuleFast.psm1
ModuleFast.tests.ps1
Test/Mocks/RequiresModule.psm1
Test/Mocks/RequiresScript.ps1

This pull request adds support for #requires statements in scripts and improves the specfile tests to be less cumbersome. The changes include adding the necessary logic to handle #requires statements in scripts and updating the specfile tests to verify individual modules and versions. Additionally, the pull request includes fixes for failing scenarios where #requires statements are missing in scripts and module manifests.

🎉 Add support for #requires in scripts and modules

---

ModuleFast.psm1
ModuleFast.tests.ps1
README.MD

ModuleFast will, if not given any specifications, search for lockfiles and Specfiles in the current directory. Multiple recursive specfile evalaution/normalization is not in scope for this change.

🎉 SpecFile Detection and LockFIles

---

ModuleFast.psm1
ModuleFast.tests.ps1

This pull request includes the following commits:
- Initial Rewrite of Local Module Find Process
- More fixups
And the following file changes:
- Refactoring of the local module find process
- Added new test case for not installing prerelease if same-version prerelease already installed

Refactor local module find process

---

ModuleFast.psm1
ModuleFast.tests.ps1
requires.lock.json

ModuleFast will now detect if a module was potentially not fully installed and reinstall it. This is done by placing a .incomplete file in install-in-progress folders and checking for it before initiating installations and clearing the folder if it is found.

🎉 Incomplete Module Handling

---

ModuleFast.psm1

ModuleFast now uses a basic module-persistent cache for origin requests.

⚡Add cache for origin requests

---

LICENSE
ModuleFast.psm1
ModuleFast.tests.ps1
Test/Mocks/Dynamic.psd1

This pull request adds support for Module Manifests with some constrained language scope. It includes changes to the Import-ModuleManifest function and related tests.

Support Module Manifests with constrained language scope

---

ModuleFast.psm1
ModuleFast.tests.ps1

ModuleFast will now check at install time if the manifest GUID does not match what was in the spec. We unfortunately cannot do this earlier in the process without fully downloading the modules, as Nuget v3 doesn't have a standard location to store the GUID for PowerShell modules in the metadata. There could potentially be a tag like "GUID:XXX-YYY-ZZZ" used for this purpose in the future.
A warning was also added against using GUID to match in general.
Closes #43.

Fix errors when GUID is not used with MaximumVersion

---

ModuleFast.psm1
ModuleFast.tests.ps1

🐛 Fix Best Candidate comparison bug

---

ModuleFast.psm1
ModuleFast.tests.ps1

Fixes #45
This pull request fixes an issue with the `Install-ModuleFast` function where it doesn't install modules in the specified destination if the same module is already installed in a different location on the system.
To address this issue, I have added a new parameter `-DestinationOnly` to the `Install-ModuleFast` function. When this parameter is specified, the function will only consider the specified destination and not any other paths currently in the `PSModulePath`. This is useful for scenarios where you want to ensure that the modules are installed in a specific location, such as in a CI environment.
I have also made changes to the `Get-ModuleFastPlan` and `Find-LocalModule` functions to support the new `-DestinationOnly` parameter.

✨ Add -DestinationOnly switch

---

ModuleFast.psm1

📄 Address Documentation Feedback

---

README.MD

Fixes quick start docs to reference the GitHub release tags more accurately.

📄 Update Pre-Release Docs

---

ModuleFast.psm1
ModuleFast.tests.ps1

NugetVersion does not detect repeated zeroes in a legacy nugetversion as being legacy and does not return the correct version type, causing the install folder to be incorrect.
Fixed #58

🐛 Handle NuGetVersion Edge Case with repeated zeroes

---

ModuleFast.psm1
ModuleFast.tests.ps1
Test/Mocks/ModuleBuilder-RequiredModules.psd1
Test/Mocks/PSDepend.psd1

The `-Path` parameter can now be directed to a manifest .psd1 or .json file of these alternate specification formats and ModuleFast will resolve and install the packages. 
ModuleFast has some limited autodetection for the format used, but in case it guesses wrong, there is also a new `-SpecFileType` parameter to explicitly define which format the file is in. Check the debug messages to see which format it detected and why.

✨ Support for PSResourceGet, RequiredModules, and PSDepend manifest files

---

ModuleFast.psm1
ModuleFast.tests.ps1

`-Scope CurrentUser` has been added to mimic the Install-Module behavior, and the automatic profile setup is excluded when done on Windows.
Fixes #64

🐛 Make CurrentUser work properly and ignore profile setup

---

ModuleFast.psm1
ModuleFast.tests.ps1

PassThru now correctly outputs installed modules handled by the install engine.
Fixes #70

-PassThru Output is broken

---

ModuleFast.psm1

Some classic paths were not casting to the correct versions, such as PowerShellGet, during a `-Update` check. Those should be working correctly now.
Fixes #69

🐛 Some classic paths not able to be processed correctly

---

ModuleFast.build.ps1
ModuleFast.psm1

ModuleFast in default specfile detection mode installs to Current Directory and not the correct destination

---

ModuleFast.build.ps1
ModuleFast.psm1

🐛 ShouldProcess fails if Debug is specified in NonInteractive Mode

---

ModuleFast.tests.ps1

As suggested at PS Summit, rename the test to have a clearer name and lock down version so the expected number doesn't need to be updated everytime Az release a new selection of modules.

:white_check_mark: update dependency test name and target version

---

ModuleFast.psm1
ModuleFast.tests.ps1

added helper function to check `powershell.config.json` for `PSModulePath`.
it will only use that when `-Destination` is not present.

fixes #89, check powershell.config.json for PSModulePath

---

ModuleFast.psm1

Resolves an issue where feeds that provide a trailing slash on their repositories and are strict on slashes (Azure Blob Storage) wouldn't resolve correctly.

🐛 Fix blob storage extra slash

---

ModuleFast.psm1
ModuleFast.tests.ps1

🐛 Modules with Trailing Zeroes do not install correctly
